### PR TITLE
Handles emojis in tweet texts

### PR DESCRIPTION
**Pull request by rezemika**
This small PR improves the handling of tweets containing emojis (now their unicode is integrated in `tweet.text`). It's probably possible to do this better however, I'd appreciate any feedback (I had some troubles with encoding...)! :)

### CODE REVIEW

**Comment by aditya-malte** [comment]
Any updates regarding this?
I think this is an important PR

**Comment by rezemika** [comment]
I don't know... I can rebase the branch on dev if @taspinar is willing to merge it.

**Comment by aditya-malte** [comment]
@taspinar , this is an important addition as emojis play an important role on twitter.
It would be great if you could review the code and merge accordingly 
Thanks

**Comment by taspinar** [comment]
Is this MR still necessary after merging #277 ?

**Comment by rezemika** [comment]
I don't think so, it's exactly the same PR (the commits are almost identical).

**Pull request closed without merging**
