### PR TITLE
Rework logging management

### PR DESCRIPTION
**Pull request by LinqLover**
See #260. Please let me know if further formalities are required!

# Changelog
- Specify constant logger name, making it easy for clients to configure loglevel of twitterscraper
- Nuke `ts_logger`
- Add `loglevel` argument to CLI

### CODE REVIEW

**Comment by LinqLover** [comment]
@taspinar Would you mind to merge or review? :-)

**Comment by simonm3** [comment]
Best practice is that the application should not set the logging level but just use its own logger or loggers. Then the user can configure their own logging including loglevel for each logger. This keeps logging independent of applications and enables you to route messages by application.

For example set at the top of each file:

`set log=logging.getLogger(__file__)`

**Comment by LinqLover** [comment]
Fair point. Can you explain your proposal more in detail? Do we have to change the twitterscraper for this at all?

**Comment by simonm3** [comment]
* delete any lines that set logging levels or formats
* change any log = getLogger() statements to log = getLogger(__file__)
* have a loglevel parameter for the cli that sets the logging level. The only place it is set should be the entry point. The only entry point within the package is the CLI. If anyone else runs it from a jupyter notebook or imports it then they can set it themselves.

**Comment by LinqLover** [comment]
Thanks for the clarification.

> - change any log = getLogger() statements to:
>   `log = getLogger(__file__)`

Are you sure about this? Wouldn't it be better to have one logger for the whole twitterscraper module? If I try this, I cannot specify the log level for twitterscraper from the outside:

```python
logging.getLogger('twitterscraper').level = logging.DEBUG
logging.getLogger().level = logging.INFO
list_of_tweets = query_tweets("Trump OR Clinton", 10)
```
Then pdb reveals that `logger.level` in `query.py` is set to `0`.

**Comment by simonm3** [comment]
AHHHH. Sorry I meant __name__

You could choose to use just "scraper". The advantage  of __name__ is that
you have slightly more control e.g. could turn on logging for scraper or
scraper.search.

**Comment by LinqLover** [comment]
Ah, I see! But this would still require every client to set the log level for each single `twitterscraper` file? Personally, I think this in an overhead for a project of this size.

**Comment by simonm3** [comment]
You can set it at module or submodule level. So if there were ts.seach and
ts.users then you can getLogger("ts").setLevel(logging.WARNING) to silence
both of them.

However using just the one logger is also fine. Any user can configure the
log message to include filename if they want it.

**Comment by LinqLover** [comment]
Well, what we could do would be to declare `logger` in each file as `logger = logging.getLogger(f'twitterscraper.{__name__}')`. That sounds interesting ...

**Comment by simonm3** [comment]
__name__ already does that so you don't have to.

**Comment by LinqLover** [comment]
Hm, I came to the conclusion that nested logger names don't scale for this project. We have basically two files that use loggers at all, `main` and `query`, of which `main` only sends a single message to the logger. For this reason, I think this PR does not need further modification. Would you agree? :)

**Comment by simonm3** [comment]
sounds good to me.

**Comment by taspinar** [comment]
Looks like an very good addition twitterscraper. Thanks for this MR.

**Comment by LinqLover** [comment]
Thanks a lot for merging!

**Pull request merged**
