### PR TITLE
query.py: URL encode colon

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by sils** [comment]
lgtm

**Comment by sils** [comment]
testing it no

**Comment by sils** [comment]
`INFO: Got 0 tweets (20 new).` seems wrong

**Comment by sils** [comment]
@adtac did you test with `--all`?

**Comment by adtac** [comment]
Yeah, I used -a (which is the same thing I think). The last time I ran it all 20 threads reached 3000+ tweets (and counting). BTW which month did this happen in for you?

**Pull request merged**
