### PR TITLE
WIP: Allow lots of tweets

### PR DESCRIPTION
**Pull request by sils**
Not fully sure if this works already so far. It seems to but I haven't tested enough yet.

### CODE REVIEW

**Comment by sils** [comment]
@taspinar it seems that the whole `pos` logic isn't completely reliable, this doesn't seem to get all tweets when comparing to the online UI - any idea?

**Comment by sils** [comment]
Seems to only occur (or at least more often) when I use multiprocessing, maybe twitter has some IP based state handling? Though when I tried gathering loads of data I noticed the same symptoms: after ~100000 tweets they just stop serving them it seems.

**Comment by taspinar** [comment]
Hi Lars,
Sorry for the long delay and thanks for this update with multiprocessing. I will merge it and also update the version on PyPi. Right now I'm trying to retrieve the URL at the moment Twitter stops serving the tweets and see how the behaviour will differ with a web browser (if there are more results available). 

For now ~100.000 tweets per 10 day time period is not that bad :)

**Comment by sils** [comment]
what I meant was: if I *don't* use multiprocessing, it seems to occur after 100000 tweets. If I *do* use multithreading it seems to affect like half of all queries.

**Pull request merged**
